### ISSUE TITLE
Gulp 4 Support?

### ISSUE THREAD

**Issue by mikeerickson** [nickdodd79/vscode-gulptasks#30]
Hey there

I am just trying this extension, however, it does not seem to support Gulp 4 tasks?

Is there something I need to do to configure it for Gulp 4, or does it not support Gulp 4

**Comment by nickdodd79** [comment]
Hey @michalstol 

Apologies for the delay in responding. I didn't see this issue come in. I am hoping to get some time soon to update the plug. Watch this space.

Nick.

**Comment by CREEATION** [comment]
@nickdodd79 🏓 🙈

**Comment by mikeerickson** [comment]
Ya I was wondering the same thing.

**Comment by CREEATION** [comment]
So, I've tinkered around a bit and it seems to be working just fine?

If this issue is about the extension not picking up on your `gulpfile.js` directory by default (instead of a `gulpfile.js` file), just edit the `gulptasks.pattern` setting to `gulpfile.js/index.js`.

Or is there something I'm missing here @mikeerickson? 🤔 

//e: Might be worth considering adding `gulpfile.js/index.js` to the default pattern to avoid further confusion. Also, I might not be writing proper Gulp 4 tasks otherwise if it doesn't fix this issue, in which case please send help 🐢
